# ==============================================================================
# Generated by qmake (2.01a) (Qt 4.4.4-temple) on: Sun 4. Jan 15:41:13 2009
# This file is generated by qmake and should not be modified by the
# user.
#  Name        : qt_build_tools.mk
#  Part of     : 
#  Description : This file is used for creating .cpp files using moc tool,
#  creating .cpp files using uic tool and creating .cpp files using rcc tool.
#  Version     : 
#
# ==============================================================================

ifeq (WINS,$(findstring WINS, $(PLATFORM)))
ZDIR=\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\release\$(PLATFORM)\$(CFG)\Z
else
ZDIR=\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\data\z
endif

TARGET = progressbar
DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH	 =  -I"..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\mkspecs\default"  -I"..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\mkspecs\default\tmp"  -I"..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtCore"  -I"..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtCore\tmp"  -I"..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtGui"  -I"..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtGui\tmp"  -I"..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include"  -I"..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\tmp"  -I"..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include"  -I"..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include\stdapis"  -I"..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include\stdapis\sys"  -I"."  -I"tmp" 

do_nothing :
	@rem do_nothing

MAKMAKE : create_temps  .\moc_progressbar.cpp  ui_progressbar.h 

.\moc_progressbar.cpp : progressbar.h
	C:\qt\qt-embedded-s60-commercial-src-4.4.4-temple\bin\moc.exe $(DEFINES)  $(INCPATH) progressbar.h -o .\moc_progressbar.cpp
ui_progressbar.h : progressbar.ui
	C:\qt\qt-embedded-s60-commercial-src-4.4.4-temple\bin\uic.exe  progressbar.ui -o ui_progressbar.h

BLD : do_nothing

CLEAN : 
	 -@ if EXIST  ".\moc_progressbar.cpp" del  ".\moc_progressbar.cpp" 
	 -@ if EXIST  "ui_progressbar.h" del  "ui_progressbar.h" 
	 -@ if EXIST  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\mkspecs\default\tmp" rmdir  /S /Q  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\mkspecs\default\tmp" 
	 -@ if EXIST  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\mkspecs\default\tmp\tmp" rmdir  /S /Q  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\mkspecs\default\tmp\tmp" 
	 -@ if EXIST  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtCore\tmp" rmdir  /S /Q  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtCore\tmp" 
	 -@ if EXIST  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtCore\tmp\tmp" rmdir  /S /Q  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtCore\tmp\tmp" 
	 -@ if EXIST  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtGui\tmp" rmdir  /S /Q  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtGui\tmp" 
	 -@ if EXIST  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtGui\tmp\tmp" rmdir  /S /Q  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtGui\tmp\tmp" 
	 -@ if EXIST  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\tmp" rmdir  /S /Q  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\tmp" 
	 -@ if EXIST  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\tmp\tmp" rmdir  /S /Q  "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\tmp\tmp" 
	 -@ if EXIST  "..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include\tmp" rmdir  /S /Q  "..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include\tmp" 
	 -@ if EXIST  "..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include\stdapis\tmp" rmdir  /S /Q  "..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include\stdapis\tmp" 
	 -@ if EXIST  "..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include\stdapis\sys\tmp" rmdir  /S /Q  "..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include\stdapis\sys\tmp" 
	 -@ if EXIST  ".\tmp" rmdir  /S /Q  ".\tmp" 
	 -@ if EXIST  "tmp\tmp" rmdir  /S /Q  "tmp\tmp" 

LIB : do_nothing

CLEANLIB : do_nothing

RESOURCE : do_nothing

FREEZE : do_nothing

SAVESPACE : do_nothing

RELEASABLES :

FINAL : do_nothing
create_temps:
	-@ if NOT EXIST "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\mkspecs\default\tmp" mkdir "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\mkspecs\default\tmp" 
	-@ if NOT EXIST "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\mkspecs\default\tmp\tmp" mkdir "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\mkspecs\default\tmp\tmp" 
	-@ if NOT EXIST "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtCore\tmp" mkdir "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtCore\tmp" 
	-@ if NOT EXIST "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtCore\tmp\tmp" mkdir "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtCore\tmp\tmp" 
	-@ if NOT EXIST "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtGui\tmp" mkdir "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtGui\tmp" 
	-@ if NOT EXIST "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtGui\tmp\tmp" mkdir "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\QtGui\tmp\tmp" 
	-@ if NOT EXIST "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\tmp" mkdir "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\tmp" 
	-@ if NOT EXIST "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\tmp\tmp" mkdir "..\..\..\..\qt\qt-embedded-s60-commercial-src-4.4.4-temple\include\tmp\tmp" 
	-@ if NOT EXIST "..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include\tmp" mkdir "..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include\tmp" 
	-@ if NOT EXIST "..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include\stdapis\tmp" mkdir "..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include\stdapis\tmp" 
	-@ if NOT EXIST "..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include\stdapis\sys\tmp" mkdir "..\..\..\..\S60\devices\S60_5th_Edition_SDK_v0.9\epoc32\include\stdapis\sys\tmp" 
	-@ if NOT EXIST ".\tmp" mkdir ".\tmp" 
	-@ if NOT EXIST "tmp\tmp" mkdir "tmp\tmp" 

